### PR TITLE
feat: add sbom described_by

### PR DESCRIPTION
**Pull request by carlosthe19916**
Based on https://github.com/trustification/trustify/issues/284#issuecomment-2193993777

image

I don't really think this is the way of showing data, but at this point I have no clue how to render the `described_by` field. So I am just rendering it to have something to show and then on a future iteration let UX and PM decide how useful/correct the `described_by` data is  and how to render it.

### CODE REVIEW

**Comment by gildub** [comment]
@carlosthe19916, I got the impression we need to wait for UXD/PM to decide what to expect and avoid leaving a trail of commented out lines of code. In the latter case we must use more explicit comments such as "// TODO - Blah-blah .." so we can track those.

**Review by gildub — COMMENTED** [review]
Please see inline.

**Comment by carlosthe19916** [comment]
@gildub thanks. I have remove all comments and added a TODO comment

**Review by gildub — APPROVED** [review]
LGTM

**Pull request merged**
